import type { Destination } from "@/lib/matching/types";

/**
 * Seeded destination data. Flight times, prices and ratings are realistic
 * approximations for an MVP — not sourced from a live travel API. Prices are
 * a blended per-person-per-night figure (amortized flight + hotel + daily
 * spend, GBP) intended for relative comparison between destinations, not as
 * a booking quote.
 */
export const DESTINATIONS: Destination[] = [
  {
    id: "marbella-spain",
    name: "Marbella",
    country: "Spain",
    region: "Costa del Sol",
    climate: "hot",
    warmMonths: [5, 6, 7, 8, 9],
    flightHoursByDeparture: { London: 2.6, Manchester: 2.9, Birmingham: 2.7, Edinburgh: 3.1 },
    basePricePerPersonPerNight: 95,
    ratings: { beach: 5, nightlife: 4, food: 4, luxury: 4, culture: 2, adventure: 2 },
    tags: ["beach", "nightlife", "luxury", "short-flight"],
  },
  {
    id: "barcelona-spain",
    name: "Barcelona",
    country: "Spain",
    region: "Catalonia",
    climate: "warm",
    warmMonths: [5, 6, 7, 8, 9],
    flightHoursByDeparture: { London: 2.1, Manchester: 2.4, Birmingham: 2.3, Edinburgh: 2.7 },
    basePricePerPersonPerNight: 90,
    ratings: { beach: 3, nightlife: 5, food: 5, luxury: 3, culture: 5, adventure: 2 },
    tags: ["city-break", "nightlife", "food", "culture"],
  },
  {
    id: "ibiza-spain",
    name: "Ibiza",
    country: "Spain",
    region: "Balearic Islands",
    climate: "hot",
    warmMonths: [5, 6, 7, 8, 9],
    flightHoursByDeparture: { London: 2.4, Manchester: 2.7, Birmingham: 2.5, Edinburgh: 2.9 },
    basePricePerPersonPerNight: 130,
    ratings: { beach: 5, nightlife: 5, food: 3, luxury: 4, culture: 1, adventure: 2 },
    tags: ["beach", "nightlife", "luxury"],
  },
  {
    id: "palma-mallorca-spain",
    name: "Palma (Mallorca)",
    country: "Spain",
    region: "Balearic Islands",
    climate: "hot",
    warmMonths: [5, 6, 7, 8, 9],
    flightHoursByDeparture: { London: 2.4, Manchester: 2.7, Birmingham: 2.5, Edinburgh: 2.9 },
    basePricePerPersonPerNight: 85,
    ratings: { beach: 5, nightlife: 3, food: 4, luxury: 3, culture: 2, adventure: 3 },
    tags: ["beach", "short-flight", "family-friendly"],
  },
  {
    id: "gran-canaria-spain",
    name: "Gran Canaria",
    country: "Spain",
    region: "Canary Islands",
    climate: "warm",
    warmMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    flightHoursByDeparture: { London: 4.2, Manchester: 4.5, Birmingham: 4.3, Edinburgh: 4.7 },
    basePricePerPersonPerNight: 75,
    ratings: { beach: 5, nightlife: 3, food: 3, luxury: 2, culture: 2, adventure: 4 },
    tags: ["beach", "winter-sun", "year-round"],
  },
  {
    id: "tenerife-spain",
    name: "Tenerife",
    country: "Spain",
    region: "Canary Islands",
    climate: "warm",
    warmMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    flightHoursByDeparture: { London: 4.3, Manchester: 4.6, Birmingham: 4.4, Edinburgh: 4.8 },
    basePricePerPersonPerNight: 78,
    ratings: { beach: 5, nightlife: 4, food: 3, luxury: 3, culture: 2, adventure: 4 },
    tags: ["beach", "winter-sun", "year-round"],
  },
  {
    id: "lanzarote-spain",
    name: "Lanzarote",
    country: "Spain",
    region: "Canary Islands",
    climate: "warm",
    warmMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    flightHoursByDeparture: { London: 4.3, Manchester: 4.6, Birmingham: 4.4, Edinburgh: 4.8 },
    basePricePerPersonPerNight: 72,
    ratings: { beach: 4, nightlife: 2, food: 3, luxury: 2, culture: 2, adventure: 5 },
    tags: ["beach", "adventure", "winter-sun"],
  },
  {
    id: "menorca-spain",
    name: "Menorca",
    country: "Spain",
    region: "Balearic Islands",
    climate: "hot",
    warmMonths: [5, 6, 7, 8, 9],
    flightHoursByDeparture: { London: 2.4, Manchester: 2.7, Birmingham: 2.5, Edinburgh: 2.9 },
    basePricePerPersonPerNight: 88,
    ratings: { beach: 5, nightlife: 2, food: 3, luxury: 3, culture: 2, adventure: 3 },
    tags: ["beach", "relaxed", "family-friendly"],
  },
  {
    id: "seville-spain",
    name: "Seville",
    country: "Spain",
    region: "Andalusia",
    climate: "hot",
    warmMonths: [4, 5, 6, 9, 10],
    flightHoursByDeparture: { London: 2.5, Manchester: 2.8, Birmingham: 2.6, Edinburgh: 3.0 },
    basePricePerPersonPerNight: 70,
    ratings: { beach: 0, nightlife: 3, food: 5, luxury: 2, culture: 5, adventure: 2 },
    tags: ["culture", "food", "city-break"],
  },
  {
    id: "lisbon-portugal",
    name: "Lisbon",
    country: "Portugal",
    region: "Lisbon Coast",
    climate: "warm",
    warmMonths: [5, 6, 7, 8, 9],
    flightHoursByDeparture: { London: 2.6, Manchester: 2.9, Birmingham: 2.7, Edinburgh: 3.1 },
    basePricePerPersonPerNight: 75,
    ratings: { beach: 2, nightlife: 4, food: 5, luxury: 2, culture: 4, adventure: 2 },
    tags: ["city-break", "food", "nightlife", "value"],
  },
  {
    id: "porto-portugal",
    name: "Porto",
    country: "Portugal",
    region: "Northern Portugal",
    climate: "mild",
    warmMonths: [6, 7, 8, 9],
    flightHoursByDeparture: { London: 2.5, Manchester: 2.8, Birmingham: 2.6, Edinburgh: 3.0 },
    basePricePerPersonPerNight: 65,
    ratings: { beach: 1, nightlife: 3, food: 5, luxury: 2, culture: 4, adventure: 2 },
    tags: ["culture", "food", "value"],
  },
  {
    id: "faro-algarve-portugal",
    name: "Faro (Algarve)",
    country: "Portugal",
    region: "Algarve",
    climate: "hot",
    warmMonths: [5, 6, 7, 8, 9],
    flightHoursByDeparture: { London: 2.7, Manchester: 3.0, Birmingham: 2.8, Edinburgh: 3.2 },
    basePricePerPersonPerNight: 80,
    ratings: { beach: 5, nightlife: 3, food: 4, luxury: 3, culture: 2, adventure: 3 },
    tags: ["beach", "golf", "family-friendly"],
  },
  {
    id: "rome-italy",
    name: "Rome",
    country: "Italy",
    region: "Lazio",
    climate: "hot",
    warmMonths: [5, 6, 7, 8, 9],
    flightHoursByDeparture: { London: 2.6, Manchester: 2.9, Birmingham: 2.7, Edinburgh: 3.2 },
    basePricePerPersonPerNight: 95,
    ratings: { beach: 1, nightlife: 3, food: 5, luxury: 3, culture: 5, adventure: 1 },
    tags: ["culture", "food", "city-break"],
  },
  {
    id: "florence-italy",
    name: "Florence",
    country: "Italy",
    region: "Tuscany",
    climate: "warm",
    warmMonths: [5, 6, 7, 8, 9],
    flightHoursByDeparture: { London: 2.4, Manchester: 2.8, Birmingham: 2.6, Edinburgh: 3.1 },
    basePricePerPersonPerNight: 100,
    ratings: { beach: 0, nightlife: 2, food: 5, luxury: 4, culture: 5, adventure: 1 },
    tags: ["culture", "food", "romantic"],
  },
  {
    id: "venice-italy",
    name: "Venice",
    country: "Italy",
    region: "Veneto",
    climate: "warm",
    warmMonths: [5, 6, 7, 8, 9],
    flightHoursByDeparture: { London: 2.2, Manchester: 2.6, Birmingham: 2.4, Edinburgh: 2.9 },
    basePricePerPersonPerNight: 110,
    ratings: { beach: 0, nightlife: 2, food: 4, luxury: 5, culture: 5, adventure: 1 },
    tags: ["culture", "luxury", "romantic"],
  },
  {
    id: "milan-italy",
    name: "Milan",
    country: "Italy",
    region: "Lombardy",
    climate: "mild",
    warmMonths: [6, 7, 8],
    flightHoursByDeparture: { London: 2.0, Manchester: 2.4, Birmingham: 2.2, Edinburgh: 2.7 },
    basePricePerPersonPerNight: 105,
    ratings: { beach: 0, nightlife: 4, food: 5, luxury: 5, culture: 4, adventure: 1 },
    tags: ["luxury", "shopping", "food", "city-break"],
  },
  {
    id: "amalfi-naples-italy",
    name: "Naples & the Amalfi Coast",
    country: "Italy",
    region: "Campania",
    climate: "hot",
    warmMonths: [5, 6, 7, 8, 9],
    flightHoursByDeparture: { London: 2.7, Manchester: 3.1, Birmingham: 2.9, Edinburgh: 3.3 },
    basePricePerPersonPerNight: 125,
    ratings: { beach: 4, nightlife: 2, food: 5, luxury: 5, culture: 4, adventure: 3 },
    tags: ["beach", "luxury", "food", "romantic"],
  },
  {
    id: "palermo-sicily-italy",
    name: "Palermo (Sicily)",
    country: "Italy",
    region: "Sicily",
    climate: "hot",
    warmMonths: [5, 6, 7, 8, 9],
    flightHoursByDeparture: { London: 3.0, Manchester: 3.3, Birmingham: 3.1, Edinburgh: 3.6 },
    basePricePerPersonPerNight: 80,
    ratings: { beach: 4, nightlife: 3, food: 5, luxury: 2, culture: 4, adventure: 2 },
    tags: ["beach", "food", "culture", "value"],
  },
  {
    id: "paris-france",
    name: "Paris",
    country: "France",
    region: "Île-de-France",
    climate: "mild",
    warmMonths: [6, 7, 8],
    flightHoursByDeparture: { London: 1.4, Manchester: 1.8, Birmingham: 1.6, Edinburgh: 2.0 },
    basePricePerPersonPerNight: 110,
    ratings: { beach: 0, nightlife: 4, food: 5, luxury: 5, culture: 5, adventure: 1 },
    tags: ["culture", "luxury", "food", "short-flight", "romantic"],
  },
  {
    id: "nice-france",
    name: "Nice",
    country: "France",
    region: "French Riviera",
    climate: "warm",
    warmMonths: [5, 6, 7, 8, 9],
    flightHoursByDeparture: { London: 2.0, Manchester: 2.3, Birmingham: 2.1, Edinburgh: 2.6 },
    basePricePerPersonPerNight: 120,
    ratings: { beach: 4, nightlife: 3, food: 4, luxury: 5, culture: 3, adventure: 2 },
    tags: ["beach", "luxury", "romantic"],
  },
  {
    id: "athens-greece",
    name: "Athens",
    country: "Greece",
    region: "Attica",
    climate: "hot",
    warmMonths: [5, 6, 7, 8, 9],
    flightHoursByDeparture: { London: 3.6, Manchester: 3.9, Birmingham: 3.7, Edinburgh: 4.1 },
    basePricePerPersonPerNight: 75,
    ratings: { beach: 2, nightlife: 4, food: 4, luxury: 2, culture: 5, adventure: 2 },
    tags: ["culture", "city-break", "value"],
  },
  {
    id: "mykonos-greece",
    name: "Mykonos",
    country: "Greece",
    region: "Cyclades",
    climate: "hot",
    warmMonths: [5, 6, 7, 8, 9],
    flightHoursByDeparture: { London: 3.9, Manchester: 4.3, Birmingham: 4.1, Edinburgh: 4.5 },
    basePricePerPersonPerNight: 140,
    ratings: { beach: 5, nightlife: 5, food: 4, luxury: 5, culture: 2, adventure: 1 },
    tags: ["beach", "nightlife", "luxury"],
  },
  {
    id: "santorini-greece",
    name: "Santorini",
    country: "Greece",
    region: "Cyclades",
    climate: "hot",
    warmMonths: [5, 6, 7, 8, 9],
    flightHoursByDeparture: { London: 3.9, Manchester: 4.3, Birmingham: 4.1, Edinburgh: 4.5 },
    basePricePerPersonPerNight: 150,
    ratings: { beach: 3, nightlife: 3, food: 4, luxury: 5, culture: 3, adventure: 1 },
    tags: ["luxury", "romantic", "beach"],
  },
  {
    id: "heraklion-crete-greece",
    name: "Heraklion (Crete)",
    country: "Greece",
    region: "Crete",
    climate: "hot",
    warmMonths: [5, 6, 7, 8, 9, 10],
    flightHoursByDeparture: { London: 3.9, Manchester: 4.2, Birmingham: 4.0, Edinburgh: 4.4 },
    basePricePerPersonPerNight: 70,
    ratings: { beach: 5, nightlife: 3, food: 4, luxury: 2, culture: 3, adventure: 3 },
    tags: ["beach", "value", "family-friendly"],
  },
  {
    id: "rhodes-greece",
    name: "Rhodes",
    country: "Greece",
    region: "Dodecanese",
    climate: "hot",
    warmMonths: [5, 6, 7, 8, 9, 10],
    flightHoursByDeparture: { London: 3.8, Manchester: 4.1, Birmingham: 3.9, Edinburgh: 4.3 },
    basePricePerPersonPerNight: 68,
    ratings: { beach: 5, nightlife: 3, food: 3, luxury: 2, culture: 3, adventure: 2 },
    tags: ["beach", "value", "family-friendly"],
  },
  {
    id: "corfu-greece",
    name: "Corfu",
    country: "Greece",
    region: "Ionian Islands",
    climate: "warm",
    warmMonths: [5, 6, 7, 8, 9],
    flightHoursByDeparture: { London: 3.2, Manchester: 3.5, Birmingham: 3.3, Edinburgh: 3.7 },
    basePricePerPersonPerNight: 72,
    ratings: { beach: 5, nightlife: 3, food: 4, luxury: 2, culture: 2, adventure: 2 },
    tags: ["beach", "family-friendly"],
  },
  {
    id: "dubrovnik-croatia",
    name: "Dubrovnik",
    country: "Croatia",
    region: "Dalmatia",
    climate: "warm",
    warmMonths: [5, 6, 7, 8, 9],
    flightHoursByDeparture: { London: 2.6, Manchester: 2.9, Birmingham: 2.7, Edinburgh: 3.2 },
    basePricePerPersonPerNight: 95,
    ratings: { beach: 4, nightlife: 3, food: 4, luxury: 3, culture: 4, adventure: 2 },
    tags: ["beach", "culture", "romantic"],
  },
  {
    id: "split-croatia",
    name: "Split",
    country: "Croatia",
    region: "Dalmatia",
    climate: "warm",
    warmMonths: [5, 6, 7, 8, 9],
    flightHoursByDeparture: { London: 2.5, Manchester: 2.8, Birmingham: 2.6, Edinburgh: 3.1 },
    basePricePerPersonPerNight: 80,
    ratings: { beach: 4, nightlife: 4, food: 4, luxury: 2, culture: 4, adventure: 3 },
    tags: ["beach", "nightlife", "culture", "value"],
  },
  {
    id: "istanbul-turkey",
    name: "Istanbul",
    country: "Turkey",
    region: "Marmara",
    climate: "mild",
    warmMonths: [5, 6, 7, 8, 9],
    flightHoursByDeparture: { London: 4.0, Manchester: 4.3, Birmingham: 4.1, Edinburgh: 4.6 },
    basePricePerPersonPerNight: 65,
    ratings: { beach: 0, nightlife: 4, food: 5, luxury: 3, culture: 5, adventure: 2 },
    tags: ["culture", "food", "value", "city-break"],
  },
  {
    id: "antalya-turkey",
    name: "Antalya",
    country: "Turkey",
    region: "Turkish Riviera",
    climate: "hot",
    warmMonths: [5, 6, 7, 8, 9, 10],
    flightHoursByDeparture: { London: 4.3, Manchester: 4.6, Birmingham: 4.4, Edinburgh: 4.9 },
    basePricePerPersonPerNight: 60,
    ratings: { beach: 5, nightlife: 3, food: 4, luxury: 4, culture: 2, adventure: 3 },
    tags: ["beach", "luxury", "value", "all-inclusive"],
  },
  {
    id: "valletta-malta",
    name: "Valletta",
    country: "Malta",
    region: "Malta",
    climate: "hot",
    warmMonths: [5, 6, 7, 8, 9],
    flightHoursByDeparture: { London: 3.1, Manchester: 3.4, Birmingham: 3.2, Edinburgh: 3.7 },
    basePricePerPersonPerNight: 78,
    ratings: { beach: 3, nightlife: 4, food: 4, luxury: 2, culture: 4, adventure: 2 },
    tags: ["beach", "culture", "nightlife"],
  },
  {
    id: "ayia-napa-cyprus",
    name: "Ayia Napa",
    country: "Cyprus",
    region: "Cyprus",
    climate: "hot",
    warmMonths: [5, 6, 7, 8, 9, 10],
    flightHoursByDeparture: { London: 4.7, Manchester: 5.0, Birmingham: 4.8, Edinburgh: 5.2 },
    basePricePerPersonPerNight: 82,
    ratings: { beach: 5, nightlife: 5, food: 3, luxury: 3, culture: 1, adventure: 2 },
    tags: ["beach", "nightlife"],
  },
  {
    id: "amsterdam-netherlands",
    name: "Amsterdam",
    country: "Netherlands",
    region: "North Holland",
    climate: "mild",
    warmMonths: [6, 7, 8],
    flightHoursByDeparture: { London: 1.2, Manchester: 1.4, Birmingham: 1.3, Edinburgh: 1.6 },
    basePricePerPersonPerNight: 100,
    ratings: { beach: 0, nightlife: 5, food: 3, luxury: 3, culture: 4, adventure: 2 },
    tags: ["nightlife", "short-flight", "city-break"],
  },
  {
    id: "berlin-germany",
    name: "Berlin",
    country: "Germany",
    region: "Berlin",
    climate: "mild",
    warmMonths: [6, 7, 8],
    flightHoursByDeparture: { London: 1.7, Manchester: 2.0, Birmingham: 1.9, Edinburgh: 2.2 },
    basePricePerPersonPerNight: 80,
    ratings: { beach: 0, nightlife: 5, food: 3, luxury: 2, culture: 5, adventure: 2 },
    tags: ["nightlife", "culture", "value"],
  },
  {
    id: "prague-czech-republic",
    name: "Prague",
    country: "Czech Republic",
    region: "Bohemia",
    climate: "mild",
    warmMonths: [6, 7, 8],
    flightHoursByDeparture: { London: 2.1, Manchester: 2.3, Birmingham: 2.2, Edinburgh: 2.6 },
    basePricePerPersonPerNight: 55,
    ratings: { beach: 0, nightlife: 5, food: 4, luxury: 2, culture: 5, adventure: 1 },
    tags: ["nightlife", "culture", "value", "stag-do"],
  },
  {
    id: "budapest-hungary",
    name: "Budapest",
    country: "Hungary",
    region: "Central Hungary",
    climate: "mild",
    warmMonths: [6, 7, 8],
    flightHoursByDeparture: { London: 2.4, Manchester: 2.7, Birmingham: 2.5, Edinburgh: 2.9 },
    basePricePerPersonPerNight: 58,
    ratings: { beach: 0, nightlife: 5, food: 4, luxury: 2, culture: 4, adventure: 1 },
    tags: ["nightlife", "culture", "value", "stag-do"],
  },
  {
    id: "vienna-austria",
    name: "Vienna",
    country: "Austria",
    region: "Vienna",
    climate: "mild",
    warmMonths: [6, 7, 8],
    flightHoursByDeparture: { London: 2.2, Manchester: 2.5, Birmingham: 2.3, Edinburgh: 2.7 },
    basePricePerPersonPerNight: 95,
    ratings: { beach: 0, nightlife: 2, food: 4, luxury: 4, culture: 5, adventure: 1 },
    tags: ["culture", "luxury"],
  },
  {
    id: "reykjavik-iceland",
    name: "Reykjavik",
    country: "Iceland",
    region: "Capital Region",
    climate: "cool",
    warmMonths: [6, 7, 8],
    flightHoursByDeparture: { London: 3.1, Manchester: 3.2, Birmingham: 3.3, Edinburgh: 2.4 },
    basePricePerPersonPerNight: 135,
    ratings: { beach: 0, nightlife: 3, food: 3, luxury: 3, culture: 2, adventure: 5 },
    tags: ["adventure", "nature", "unique"],
  },
  {
    id: "marrakech-morocco",
    name: "Marrakech",
    country: "Morocco",
    region: "Marrakech-Safi",
    climate: "hot",
    warmMonths: [3, 4, 5, 9, 10, 11],
    flightHoursByDeparture: { London: 3.6, Manchester: 3.9, Birmingham: 3.7, Edinburgh: 4.1 },
    basePricePerPersonPerNight: 62,
    ratings: { beach: 0, nightlife: 2, food: 4, luxury: 4, culture: 5, adventure: 4 },
    tags: ["culture", "adventure", "luxury", "value"],
  },
  {
    id: "sharm-el-sheikh-egypt",
    name: "Sharm El Sheikh",
    country: "Egypt",
    region: "South Sinai",
    climate: "hot",
    warmMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    flightHoursByDeparture: { London: 5.3, Manchester: 5.6, Birmingham: 5.4, Edinburgh: 5.9 },
    basePricePerPersonPerNight: 68,
    ratings: { beach: 5, nightlife: 2, food: 3, luxury: 4, culture: 2, adventure: 4 },
    tags: ["beach", "all-inclusive", "adventure", "winter-sun"],
  },
  {
    id: "hurghada-egypt",
    name: "Hurghada",
    country: "Egypt",
    region: "Red Sea",
    climate: "hot",
    warmMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    flightHoursByDeparture: { London: 5.4, Manchester: 5.7, Birmingham: 5.5, Edinburgh: 6.0 },
    basePricePerPersonPerNight: 60,
    ratings: { beach: 5, nightlife: 2, food: 3, luxury: 3, culture: 1, adventure: 4 },
    tags: ["beach", "all-inclusive", "value", "winter-sun"],
  },
  {
    id: "dubai-uae",
    name: "Dubai",
    country: "United Arab Emirates",
    region: "Dubai",
    climate: "hot",
    warmMonths: [10, 11, 12, 1, 2, 3, 4],
    flightHoursByDeparture: { London: 7.1, Manchester: 7.4, Birmingham: 7.2, Edinburgh: 7.7 },
    basePricePerPersonPerNight: 165,
    ratings: { beach: 4, nightlife: 4, food: 4, luxury: 5, culture: 2, adventure: 3 },
    tags: ["luxury", "beach", "shopping", "long-flight"],
  },
  {
    id: "phuket-thailand",
    name: "Phuket",
    country: "Thailand",
    region: "Southern Thailand",
    climate: "hot",
    warmMonths: [11, 12, 1, 2, 3],
    flightHoursByDeparture: { London: 11.5, Manchester: 13.5, Birmingham: 13.0, Edinburgh: 14.0 },
    basePricePerPersonPerNight: 100,
    ratings: { beach: 5, nightlife: 4, food: 4, luxury: 3, culture: 2, adventure: 4 },
    tags: ["beach", "long-flight", "adventure"],
  },
  {
    id: "bangkok-thailand",
    name: "Bangkok",
    country: "Thailand",
    region: "Central Thailand",
    climate: "hot",
    warmMonths: [11, 12, 1, 2, 3],
    flightHoursByDeparture: { London: 11.5, Manchester: 13.5, Birmingham: 13.0, Edinburgh: 14.0 },
    basePricePerPersonPerNight: 85,
    ratings: { beach: 1, nightlife: 5, food: 5, luxury: 3, culture: 4, adventure: 3 },
    tags: ["nightlife", "food", "culture", "long-flight", "value"],
  },
  {
    id: "new-york-usa",
    name: "New York",
    country: "United States",
    region: "New York",
    climate: "mild",
    warmMonths: [5, 6, 7, 8, 9],
    flightHoursByDeparture: { London: 7.8, Manchester: 8.3, Birmingham: 9.5, Edinburgh: 9.8 },
    basePricePerPersonPerNight: 175,
    ratings: { beach: 0, nightlife: 5, food: 5, luxury: 4, culture: 5, adventure: 2 },
    tags: ["city-break", "nightlife", "culture", "long-flight"],
  },
  {
    id: "miami-usa",
    name: "Miami",
    country: "United States",
    region: "Florida",
    climate: "hot",
    warmMonths: [1, 2, 3, 4, 11, 12],
    flightHoursByDeparture: { London: 9.4, Manchester: 10.2, Birmingham: 11.0, Edinburgh: 11.3 },
    basePricePerPersonPerNight: 160,
    ratings: { beach: 5, nightlife: 5, food: 4, luxury: 5, culture: 2, adventure: 2 },
    tags: ["beach", "nightlife", "luxury", "long-flight"],
  },
  {
    id: "cancun-mexico",
    name: "Cancún",
    country: "Mexico",
    region: "Yucatán Peninsula",
    climate: "hot",
    warmMonths: [11, 12, 1, 2, 3, 4],
    flightHoursByDeparture: { London: 10.5, Manchester: 11.3, Birmingham: 12.0, Edinburgh: 12.4 },
    basePricePerPersonPerNight: 130,
    ratings: { beach: 5, nightlife: 4, food: 3, luxury: 4, culture: 3, adventure: 4 },
    tags: ["beach", "all-inclusive", "long-flight"],
  },
  {
    id: "punta-cana-dominican-republic",
    name: "Punta Cana",
    country: "Dominican Republic",
    region: "La Altagracia",
    climate: "hot",
    warmMonths: [11, 12, 1, 2, 3, 4],
    flightHoursByDeparture: { London: 9.2, Manchester: 10.0, Birmingham: 10.7, Edinburgh: 11.0 },
    basePricePerPersonPerNight: 120,
    ratings: { beach: 5, nightlife: 3, food: 3, luxury: 4, culture: 1, adventure: 2 },
    tags: ["beach", "all-inclusive", "long-flight"],
  },
  {
    id: "dublin-ireland",
    name: "Dublin",
    country: "Ireland",
    region: "Leinster",
    climate: "mild",
    warmMonths: [6, 7, 8],
    flightHoursByDeparture: { London: 1.3, Manchester: 1.1, Birmingham: 1.2, Edinburgh: 1.1 },
    basePricePerPersonPerNight: 85,
    ratings: { beach: 0, nightlife: 5, food: 3, luxury: 2, culture: 3, adventure: 1 },
    tags: ["nightlife", "short-flight", "stag-do"],
  },
  {
    id: "sal-cape-verde",
    name: "Sal",
    country: "Cape Verde",
    region: "Sal Island",
    climate: "warm",
    warmMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    flightHoursByDeparture: { London: 6.0, Manchester: 6.3, Birmingham: 6.1, Edinburgh: 6.6 },
    basePricePerPersonPerNight: 95,
    ratings: { beach: 5, nightlife: 2, food: 2, luxury: 3, culture: 1, adventure: 3 },
    tags: ["beach", "winter-sun", "all-inclusive"],
  },
];

export function findDestinationById(id: string): Destination | undefined {
  return DESTINATIONS.find((destination) => destination.id === id);
}
